x = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(x)))
print('Só tem espaço? {}'.format(x.isspace()))
print('É um número? {}'.format(x.isnumeric()))
print('É alfabético? {}'.format(x.isalpha()))
print('É alfanumérico? {}'.format(x.isalnum()))
print('Está maiúsculo? {}'.format(x.isupper()))
print('Está minúsculo? {}'.format(x.islower()))
print('Está captalizada? {}'.format(x.istitle()))
