print('====== DESAFIO 04 ======')

x = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(x))
print('Só tem espaços? ', x.isspace())
print('É um número? ', x.isnumeric())
print('É alfabético? ', x.isalpha())
print('É alfanumérico? ', x.isalnum())
print('Está em maíusculas? ', x.isupper())
print('Está em minúsculas? ', x.islower())
print('Está captalizado? ', x.istitle())